
[build]
  base = "Frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


# Handle API redirects to your backend
[[redirects]]
  from = "/api/*"
  to = "https://paul-to-thesis-graduation-1.onrender.com/api/:splat"
  status = 200
  force = true


[[plugins]]
  package = "@netlify/plugin-nextjs"