import type { Metadata } from "next";
import Itim from "next/font/local";
import Nunito_Sans from "next/font/local";
import "./globals.css";
import { I18nextProvider } from "react-i18next";
import i18n from "@/i18n/i18n";

const nunito = Nunito_Sans({
  variable: "--font-nunito",
  src: [{
    path: '../../public/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf',
    weight: '100 900',
    style: 'normal',
  },
  {
    path: '../../public/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf',
    weight: '100 900',
    style: 'italic',
  }
],
});

const itim = Itim({
  variable: "--font-itim",
  src: [
    { path: '../../public/fonts/Itim-Regular.ttf', weight: '400', style: 'normal' },
  ],
});


export const metadata: Metadata = {
  title: "NFeam House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${itim.variable} antialiased`}
      >
         <I18nextProvider i18n={i18n}> 
          {children}
    </I18nextProvider>
      </body>
    </html>
  );
}
