import Link from 'next/link';
import type { Metadata } from "next";
import Itim from "next/font/local";
import Nunito_Sans from "next/font/local";
import "./globals.css";

const nunito = Nunito_Sans({
    variable: "--font-nunito",
    src: [{
        path: '../../../public/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf',
        weight: '100 900',
        style: 'normal',
    },
    {
        path: '../../../public/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf',
        weight: '100 900',
        style: 'italic',
    }
    ],
});

const itim = Itim({
    variable: "--font-itim",
    src: [
        { path: '../../../public/fonts/Itim-Regular.ttf', weight: '400', style: 'normal' },
    ],
});

export const metadata: Metadata = {
    title: "NFeam House",
    description: "Generated by create next app",
};

export default function LangLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: { lang: string };
}) {
    const otherLang = params.lang === 'en' ? 'vi' : 'en';

    return (
        <html lang={params.lang}>
            <body
                className={`${nunito.variable} ${itim.variable} antialiased`}
            >
                <nav>
                    <Link href={`/${otherLang}`}>Switch to {otherLang.toUpperCase()}</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
